### ISSUE TITLE
关于etcd一致性的问题

### ISSUE THREAD

**Issue by fatedier** [ngaut/zkhelper#7]
使用etcd集群部署codis的时候遇到的一个问题，初始化slot失败：
[https://github.com/wandoulabs/codis/issues/444](https://github.com/wandoulabs/codis/issues/444)

我又看了下 codis 和 etcd 的代码，发现etcd的get操作如果不加 `quorum=true` 的话并不能保证强一致性。而codis中这部分使用了 zkhelper 这个库，zkhelper 中对etcd的操作是用的 go-etcd 这个库，go-etcd默认是使用的 WEAK_CONSISTENCY

```go
// NewClient create a basic client that is configured to be used
// with the given machine list.
func NewClient(machines []string) *Client {
    config := Config{
        // default timeout is one second
        DialTimeout: time.Second,
        Consistency: WEAK_CONSISTENCY,
    }   

    client := &Client{
        cluster: NewCluster(machines),
        config:  config,
    }   

    client.initHTTPClient()
    client.saveConfig()

    return client
}
```

那么在codis中初始化slot的操作 创建一个顺序的文件，删除这个文件，创建同名的目录中，其中删除操作

```go
defer e.pool.Put(conn)
c := conn.(*PooledEtcdClient).c

resp, err := c.Get(key, true, false)
if resp == nil {
    return convertToZkError(err)
}

if resp.Node.Dir {
    _, err = c.DeleteDir(key)
} else {
    _, err = c.Delete(key, false)
}
```

这里如果不是强一致性的话，并且连接是从连接池中获取的新的连接，并不能保证删除掉之前创建的文件，后面创建同名目录的时候就会失败。

zkhelper这个库中是否应该增加一个设置为强一致性的接口，对应go-etcd中的
`func (c *Client) SetConsistency(consistency string)`

或者修改codis中初始化部分的逻辑？

**Comment by ngaut** [comment]
Right, You may change the source of zkhelper, And send me an PR. 
And we should use strong consistency by default.
Thanks.
